//{Do not edit this file}
//Gagah1 generated include file
//Used by Rsrc.rc


#define IDM_MENU      100
#define IDC_HAND2     101
#define IDI_SPHINX      102
#define IDB_CLAVIER      103
#define IDB_BLOCCMD      104
#define IDB_BLOCBTN      105
#define IDB_MUTE         106
#define IDB_TOOLBOX2     107
#define IDB_SLIDER       108
#define IDB_KNOB1        109
#define IDB_KNOB2        110
#define IDB_LED        111
#define IDM_MENUHELP     112
#define IDC_CHISEL       113
#define IDC_STICK        114
#define IDC_RUBBER       115
#define IDC_BIGCROSS     116
#define IDB_PAN          117

#define IDD_DLGPATH      120
#define IDD_DLGWAVEIN    121
#define IDD_DLGFORMAT    122
#define IDD_DLGCLICK     123
#define IDD_DLGINFO      124
#define IDD_DLGDEVICE    125
#define IDD_DLGRECORD    126
#define IDD_DLGHELP      127

#define IDM_FILENEW      40001
#define IDM_FILEOPEN      40002
#define IDM_FILESAVE      40003
#define IDM_FILESAVEAS      40004
#define IDM_FILECLOSE      40005
#define IDM_FILEIMPORT      40006
#define IDM_FILEEXPORT      40007
#define IDM_FILEWAVEIN      40008
#define IDM_FILEEXIT      40009

#define IDM_CANCEL      40010
#define IDM_RESUME      40011
#define IDM_SELECTALL      40012

#define IDM_SIGNATURE      40020
#define IDM_TEMPO      40021
#define IDM_CLICK      40022
#define IDM_NEWTRACK      40023
#define IDM_DELETETRACK      40024
#define IDM_INFOPATTERN      40025
#define IDM_MIDIDEVICE      40026
#define IDM_MIDIOPTION      40027

#define IDM_GRID      40030
#define IDM_WHITEBACKGROUND      40031
#define IDM_OBJECTCOLOR      40032

#define IDM_WNDARRANGE      40040
#define IDM_WNDCOMMAND      40041
#define IDM_WNDLIST      40042
#define IDM_WNDMATRIX      40043
#define IDM_WNDMIXER      40044

#define IDM_ABOUTHELP      40050
#define IDM_HELPFILE      40051

// menu d'aide
#define IDM_HELP_BACK       20000
#define IDM_HELP_NEXT       20001
#define IDM_HELP_FIRST      20010
#define IDM_HELP_LAST       20019

// ids pour la boite de dialogue enregistrement WAVE
#define IDC_STARTEDIT     1000
#define IDC_ENDEDIT      1001
#define IDC_PROGRESS      1002
#define IDC_FREQUENCY      1003
#define IDC_RESOLUTION      1004
#define IDC_MODE        1005
#define IDC_FORMAT        1006

// ids pour la boite de dialogue metronome
#define IDC_ACTIVE1        1010
#define IDC_ACTIVE2        1011
#define IDC_NOTE1         1012
#define IDC_NOTE2         1013
#define IDC_VELOCITY1        1014
#define IDC_VELOCITY2        1015
#define IDC_CHANNEL1        1016
#define IDC_CHANNEL2        1017

// ids pour la boite de dialogue info séquence
#define IDC_LYRIC         1020
#define IDC_COPYRIGHT         1021
#define IDC_TEXT         1022
#define IDC_MARKER         1023
#define IDC_CUEPOINT         1024
#define IDC_INCLUDE         1025

// ids pour la boite de dialogue Peripherique MIDI
#define IDC_CBMIDIOUT         1030
#define IDC_CBMIDIIN         1031

// ids pour la boite de dialogue Options d'enregistrement
#define IDC_ONETRACK         1040
#define IDC_MORETRACK         1041
#define IDC_ONCLICK         1042
#define IDC_FUSION         1043
#define IDC_ONQUANTISE         1044
#define IDC_CBQUANTISE         1045
#define IDC_FILTER_NOTE         1050
#define IDC_FILTER_KEYPRESS         1051
#define IDC_FILTER_CTRLCHANGE         1052
#define IDC_FILTER_PRGMCHANGE         1053
#define IDC_FILTER_CHANPRESS         1054
#define IDC_FILTER_PITCHBEND         1055
#define IDC_FILTER_SYSEX         1056

#define IDC_EDITHELP         1070
