#ifndef _STANDARD_HEADER_H_
#define _STANDARD_HEADER_H_

static char szInstrumentName[][32] = {"Grand Piano", "Bright Piano", "Electric Grand",
    "Honky-tonk piano", "Electric piano 1", "Electric piano 2", "Harpsichord", "Clavinet",
    "Celesta", "Glockenspiel", "Music box", "Vibraphone",
    "Marimba", "Xylophone", "Tubular bells", "Dulcimer",
    "Organ 1", "Organ 2", "Organ 3", "Church organ",
    "Reed organ", "Accordion", "Harmonica", "Bandneon",
    "Nylon guitar", "Steel guitar", "Jazz guitar", "Clean guitar",
    "Muted guitar", "Overdrive guitar", "Distortion guitar", "Guitar harminics",
    "Acoustic bass", "Fingered bass", "Picked bass", "Fretless bass",
    "Slap bass 1", "Slap bass 2", "Synth bass 1", "Synth bass 2",
    "Violin", "Viola", "Cello", "Contrabass",
    "Tremolo strings", "Pizzicato strings", "Harp", "Timpani",
    "String ensemble 1", "String ensemble 2", "Synth strings 1", "Synth strings 2",
    "Choir Aahs", "Choir Oohs", "Synth voice", "Orchestra hit",
    "Trumpet", "Trombone", "Tuba", "Muted trumpet",
    "French horn", "Brass section", "Synth brass 1", "Synth brass 2",
    "Soprano sax", "Alto sax", "Tenor sax", "Baritone sax",
    "Oboe", "English horn", "Bassoon", "Clarinet",
    "Piccolo", "Flute", "Recorder", "Pan flute",
    "Blown bottle", "Shakuhachi", "Whistle", "Ocarina",
    "Square synth", "Saw synth", "Synth caliope", "Chiff lead",
    "Charang", "Solo voice", "5th Saw wave", "Bass lead",
    "Fantasia", "Warm pad", "Polysynth", "Synthchoir",
    "Bowed glass", "Metal pad", "Halo pad", "Sweep pad",
    "Rain", "Soundtrack", "Cristal rain", "Atmosphere",
    "Brightness", "Goblins", "Echoes", "Sci-fi",
    "Sitar", "Banjo", "Shamisen", "Koto",
    "Kalimbar", "Bag pipe", "Fiddle", "Shanai",
    "Tinkle bell", "Agogo", "Steel drums", "Woodblock",
    "Taiko drum", "Melodic tom", "Synth drum", "Reverse cymbal",
    "Fret noise", "Breath noise", "Seashore", "Bird tweet",
    "Telephone ring", "Helicopter", "Applause", "Gunshot"};

static char szControllerName[][32] = {"Bank MSB", "Modulation", "Breath", "Ctrl 3",
    "Foot Control", "Portamento", "Data MSB", "Volume",
    "Balance", "Ctrl 9", "Pan", "Expression",
    "Ctrl effet 1", "Ctrl effet 2", "Ctrl 14", "Ctrl 15",
    "General 1", "General 2", "General 3", "General 4",
    "Ctrl 20", "Ctrl 21", "Ctrl 22", "Ctrl 23",
    "Ctrl 24", "Ctrl 25", "Ctrl 26", "Ctrl 27",
    "Ctrl 28", "Ctrl 29", "Ctrl 30", "Ctrl 31",
    "Bank LSB", "Modulation", "Breath", "Ctrl 3",
    "Foot Control", "Portamento", "Data LSB", "Volume",
    "Balance", "Ctrl 9 LSB", "Pan", "Expression",
    "Ctrl effet 1", "Ctrl effet 2", "Ctrl 14 LSB", "Ctrl 15 LSB",
    "General 1", "General 2", "General 3", "General 4",
    "Ctrl 20 LSB", "Ctrl 21 LSB", "Ctrl 22 LSB", "Ctrl 23 LSB",
    "Ctrl 24 LSB", "Ctrl 25 LSB", "Ctrl 26 LSB", "Ctrl 27 LSB",
    "Ctrl 28 LSB", "Ctrl 29 LSB", "Ctrl 30 LSB", "Ctrl 31 LSB",
    "Sustain", "Portamento", "Sostemeto", "Soft pedal",
    "Legato", "Hold 2", "Ctrl 70", "Resonance",
    "Release time", "Attack time", "LPF Cutoff", "Ctrl 75",
    "Ctrl 76", "Ctrl 77", "Ctrl 78", "Ctrl 79",
    "Ctrl 80", "Ctrl 81", "Ctrl 82", "Ctrl 83",
    "Ctrl 84", "Ctrl 85", "Ctrl 86", "Ctrl 87",
    "Ctrl 88", "Ctrl 89", "Ctrl 90", "Reverb",
    "Tremolo", "Chorus depth", "Vibrato", "Phaser",
    "Data increm.", "Data decrem.", "Param non reg LSB", "Param non reg MSB",
    "Param reg LSB", "Param reg MSB", "Ctrl 102", "Ctrl 103",
    "Ctrl 104", "Ctrl 105", "Ctrl 106", "Ctrl 107",
    "Ctrl 108", "Ctrl 109", "Ctrl 110", "Ctrl 111",
    "Ctrl 112", "Ctrl 113", "Ctrl 114", "Ctrl 115",
    "Ctrl 116", "Ctrl 117", "Ctrl 118", "Ctrl 119",
    "All sound off", "Reset all controls", "Local mode", "All notes off",
    "Omni off mode", "Omni on mode", "Monophonic mode", "Polyphonic mode"};
    
    
#endif
